from .seedance25_nodes import (
    NODE_CLASS_MAPPINGS as _NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _NODE_DISPLAY_NAME_MAPPINGS,
)
from .seedance25_video_saver import (
    NODE_CLASS_MAPPINGS as _SAVER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _SAVER_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {**_NODE_CLASS_MAPPINGS, **_SAVER_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {
    **_NODE_DISPLAY_NAME_MAPPINGS,
    **_SAVER_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
